import AppKit

/// `NSPasteboard.general.changeCount` のポーリング監視（§5.1）。
/// macOS にはクリップボード変更のコールバック API が無いため、業界標準どおりのポーリング方式。
/// 間隔 0.5 秒 + ポップアップ／メニューを開く直前の即時チェックで体感レイテンシを消す。
@MainActor
final class ClipboardMonitor {
    private let pasteboard = NSPasteboard.general
    private let settings: SettingsStore
    private let history: HistoryService
    private var timer: Timer?
    private var lastObservedChangeCount: Int

    /// PasteService（Phase 2.4 以降）が自分で書き込んだ changeCount。
    /// 自己ペーストの再取り込みで履歴が並び替わるのを防ぐ（§5.3 [1] / §7 [4]）
    var ignoredChangeCount: Int?

    /// nspasteboard.org 標準マーカーのうち**常に**破棄するもの（§5.3 [2]）。
    /// ConcealedType は別扱い: 設定 `skipConcealedContent`（O-3）で破棄/保存を切替
    private static let alwaysSkipMarkers: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),    // 一時データ宣言
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType") // プログラム生成
    ]

    /// パスワードマネージャが付ける秘匿マーカー（O-1/O-2/O-3）
    private static let concealedMarker = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")

    init(settings: SettingsStore, history: HistoryService) {
        self.settings = settings
        self.history = history
        // 起動前からペーストボードに載っていた内容は取り込まない
        lastObservedChangeCount = pasteboard.changeCount
    }

    func start() {
        guard timer == nil else { return }
        let newTimer = Timer(timeInterval: settings.pollingInterval, repeats: true) { [weak self] _ in
            Task { @MainActor [weak self] in
                self?.checkForChanges()
            }
        }
        RunLoop.main.add(newTimer, forMode: .common)
        timer = newTimer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    /// ポップアップ／メニューを開く直前にも呼ぶこと（コピー直後に開いたときの取りこぼし防止 §5.1）
    func checkForChanges() {
        let changeCount = pasteboard.changeCount
        guard changeCount != lastObservedChangeCount else { return }
        lastObservedChangeCount = changeCount
        guard changeCount != ignoredChangeCount else { return }
        capture()
    }

    private func capture() {
        // [2] マーカー検査
        let types = pasteboard.types ?? []
        // Transient / AutoGenerated は設定によらず常にメモリ上にも残さず即破棄
        guard !types.contains(where: Self.alwaysSkipMarkers.contains) else { return }

        let hasConcealed = types.contains(Self.concealedMarker)
        // ConcealedType は設定で破棄/保存を切替（O-3）。既定は破棄（=skipConcealedContent true）
        if hasConcealed, settings.skipConcealedContent { return }

        // [3] 除外アプリ判定（C-6）。frontmost は「コピー操作をしたアプリ」の近似
        // （バックグラウンド書き込みは判別不能 — Clipy/Maccy と同じ既知の限界 §5.3）
        if let bundleID = NSWorkspace.shared.frontmostApplication?.bundleIdentifier,
           settings.excludedBundleIdentifiers.contains(bundleID) {
            return
        }

        // [4] representation 抽出（§5.2）
        guard var content = CapturedContent.read(from: pasteboard) else { return }
        content.hasConcealedMarker = hasConcealed

        // [5]〜[9] ハッシュ・重複・機微判定・振り分け・上限執行は HistoryService（§5.3）
        Task {
            await history.ingest(content)
        }
    }
}
